project: learning-agency-lab-pil-data-detection
name: experiment-tracking-Learning-Agency-Lab-PII-Data-Detection
wandb:
  WANDB_API_KEY: WANDB_API_KEY
  entity: baolocpham
  project: learning-agency-lab-pil-data-detection
  name: learning-agency-lab-pil-data-detection
  group: learning-agency-lab-pil-data-detection_training
  job_type: Train_Supervised
parameters:
  root_data_dir: "./data"
  grade_data_dir: "./data"
  n_fold: 4
  save_model_dir: "./outputs"
  preprocess_text: False
  debug: False
  
  train_stage_1:
    select: "base"
    base_model_name: "microsoft/deberta-v3-{select}"
    model_path: ""
    output_dir: "./"
    freeze_embeddings: False
    freeze_n_layers: 6
    seed: 42
    batch_size: 2
    learning_rate: 1e-5
    num_train_epochs: 2
    per_device_train_batch_size: 2
    per_device_eval_batch_size: 4
    report_to: "none"
    evaluation_strategy: "epoch"
    save_strategy: "epoch"
    save_total_limit: 1
    overwrite_output_dir: True
    load_best_model_at_end: True
    lr_scheduler_type: 'cosine'
    metric_for_best_model: "f1"
    greater_is_better: True
    weight_decay: 0.01


  inference_stage_1:
    is_ensemble: False
    input_prepared_dir: "./"
    input_prepared_file: "test.csv"
    select: "base"
    model_name: "microsoft/deberta-v3-{select}"
    only_model_name: "deberta-v3-{select}"
    n_fold: 4
    fold_to_inference: 0
    batch_size: 32
    freezing: False
    max_len: 32
    pooling: "GemText"
    load_model_dir: ""
    output_dir: ""
    have_next_stage: False
    output_file: "stage_1_output.csv"